displayName: Request Body Rewrite
summary: Middleware with ability to replace request body with with regex
type: middleware
import: github.com/maretodoric/traefik-plugin-requestbodyrewrite

testData:
  methods:
    - PUT
  rewrites:
    - regex: foo
      replacement: bar
